% load the SAVI data
fname = 'CrossCZO_StormEvents_StreamChemistry_data_AllSites.csv';
if exist(fname,'file')
    TSAVI = readtable(fname);
else % download data from the hydroshare repository
    data_url = 'https://www.hydroshare.org/resource/89cfde573936487a9ab4ff406638465b/data/contents/CrossCZO_StormEvents_StreamChemistry_data_AllSites.csv';
    TSAVI = webread(data_url);
end

% edit the data for improved readability
oldnames = {'Kwakshua Watershed 708','Elder Creek','La Jara','Providence Creek (P303)','Quiock Creek','Sapine'};
newname = {'Hakai','Elder','La Jara','Providence','Quiock','Sapine'};
for i = 1:length(oldnames)
    oldname = oldnames{i};
    TSAVI.catchment(strcmp(TSAVI.catchment,oldname)) = newname(i);
end
catch_list = unique(TSAVI.catchment);

% some plot settings
col = lines(length(catch_list));
mkstyle = 'd';
siz = 10;
alph = .7;
alph_bar = .5;

% col = [ 0.1    0.8970    0.1410;...
%     0.9500    0.4250    0.0980;...
%     0.4940    0.1840    0.5560;...
%     0.4660    0.6740    0.1880;...
%     0.3010    0.7450    0.9330;...
%     0.6350    0.0780    0.1840];


% col = [         0    0    0.4410;...
%     0.8500    0.3250    0.0980;...
%     0.9290    0.6940    0.1250;...
%     0.4940    0.1840    0.5560;...
%     0.4660    0.6740    0.1880;...
%     0.3010    0.7450    0.9330];

col = 1/256 *[...
      0, 123,  49;...
    123, 214, 247;...
     41, 115, 181;...
    240,  90, 115;...
    180,  24, 107;...
    214, 189,   8;...
    ];

figure
set(gcf,'color','white');

sp1 = subplot(1,2,1);
set(sp1,'NextPlot','add','TickDir','out','XScale','log',...
    'XLim',[0.002 18],'box','on')
axis square
xlabel('runoff [mm/h]')
ylabel(['\delta ^{30}Si [',char(8240),']'])
for i = 1:length(catch_list)
    % select data from a catchment
    qq = strcmp(TSAVI.catchment,catch_list(i));
    e = errorbar(TSAVI.runoff_mm_day_(qq)/24,TSAVI.capdelta_30Si_diss_rock_perMil_(qq),TSAVI.capdelta_30Si_diss_rock_2sd_perMil_(qq),...
        mkstyle,...
        'MarkerSize',0.1,...
        'Color',[.8 .8 .8],...
        'LineWidth',.5,...
        'MarkerFaceColor',col(i,:),...
        'CapSize',0,...
        'DisplayName',catch_list{i},...
        'HandleVisibility','off');
    % Set errorbar transparency (undocumented)
    set([e.Bar, e.Line], 'ColorType', 'truecoloralpha', 'ColorData', [e.Line.ColorData(1:3); 255*alph_bar])
end
for i = 1:length(catch_list)
    % select data from a catchment
    qq = strcmp(TSAVI.catchment,catch_list(i));
    scatter(TSAVI.runoff_mm_day_(qq)/24,TSAVI.capdelta_30Si_diss_rock_perMil_(qq),...
        siz,...
        col(i,:),...
        mkstyle,...
        'MarkerFaceColor',col(i,:),...
        'MarkerFaceAlpha',alph-0.4,...
        'MarkerEdgeColor',col(i,:),...
        'MarkerEdgeAlpha',alph,...
        'DisplayName',catch_list{i},...
        'HandleVisibility','on')
end

legend(sp1,'Location','SouthOutside')

sp2 = subplot(1,2,2);
set(sp2,'NextPlot','add','TickDir','out',...
    'XLim',[0 1.3],'box','on')
axis square
xlabel('f_{diss} Si [-]')
ylabel(['\delta ^{30}Si [',char(8240),']'])
for i = 1:length(catch_list)
    % select data from a catchment
    qq = strcmp(TSAVI.catchment,catch_list(i));
    e = errorbar(TSAVI.fSi_diss(qq),TSAVI.capdelta_30Si_diss_rock_perMil_(qq),TSAVI.capdelta_30Si_diss_rock_2sd_perMil_(qq),...
        mkstyle,...
        'MarkerSize',0.1,...
        'Color',[.8 .8 .8],...
        'LineWidth',.5,...
        'MarkerFaceColor',col(i,:),...
        'CapSize',0,...
        'DisplayName',catch_list{i},...
        'HandleVisibility','off');
    % Set errorbar transparency (undocumented)
    set([e.Bar, e.Line], 'ColorType', 'truecoloralpha', 'ColorData', [e.Line.ColorData(1:3); 255*alph_bar])
end
for i = 1:length(catch_list)
    % select data from a catchment
    qq = strcmp(TSAVI.catchment,catch_list(i));
    scatter(TSAVI.fSi_diss(qq),TSAVI.capdelta_30Si_diss_rock_perMil_(qq),...
        siz,...
        col(i,:),...
        mkstyle,...
        'MarkerFaceColor',col(i,:),...
        'MarkerFaceAlpha',alph-0.4,...
        'MarkerEdgeColor',col(i,:),...
        'MarkerEdgeAlpha',alph,...
        'DisplayName',catch_list{i},...
        'HandleVisibility','on')
end





